//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticketTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClosedTicket
    {
        public int idsClosedTicket { get; set; }
        public Nullable<int> idsTicket { get; set; }
        public System.DateTime dtmResolved { get; set; }
        public string txtUserName { get; set; }
        public bool blnResolved { get; set; }
        public string txtResolution { get; set; }
    
        public virtual tblOpenTicket tblOpenTicket { get; set; }
    }
}
