//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticketTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpenTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOpenTicket()
        {
            this.tblClosedTickets = new HashSet<tblClosedTicket>();
        }
    
        public int idsTicket { get; set; }
        public string txtUserName { get; set; }
        public System.DateTime dtmCreated { get; set; }
        public Nullable<System.DateTime> dtmResolved { get; set; }
        public bool blnResolved { get; set; }
        public string txtIssue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClosedTicket> tblClosedTickets { get; set; }
    }
}
